# Generated by Django 5.2.8 on 2025-11-18 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the meal (e.g., 'Breakfast', 'Chicken Salad').", max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the meal was logged.')),
                ('total_weight', models.FloatField(help_text='Total weight of the meal (g).')),
                ('total_total_fat', models.FloatField(help_text='Total fat (g).', verbose_name='Total Fat')),
                ('total_saturated_fat', models.FloatField(help_text='Saturated fat (g).', verbose_name='Saturated Fat')),
                ('total_total_carbs', models.FloatField(help_text='Total carbohydrates (g).', verbose_name='Total Carbs')),
                ('total_fiber', models.FloatField(help_text='Dietary fiber (g).', verbose_name='Fiber')),
                ('total_sugar', models.FloatField(help_text='Sugar (g).', verbose_name='Sugar')),
                ('total_sodium', models.FloatField(help_text='Sodium (mg).', verbose_name='Sodium')),
                ('total_potassium', models.FloatField(help_text='Potassium (mg).', verbose_name='Potassium')),
                ('total_cholesterol', models.FloatField(help_text='Cholesterol (mg).', verbose_name='Cholesterol')),
                ('user', models.ForeignKey(help_text='The user who logged this meal.', on_delete=django.db.models.deletion.CASCADE, related_name='meal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ingredient.', max_length=100)),
                ('weight', models.FloatField(help_text='Weight of the ingredient used (g).')),
                ('total_fat', models.FloatField(help_text='Fat content (g).', verbose_name='Total Fat')),
                ('saturated_fat', models.FloatField(help_text='Saturated fat content (g).', verbose_name='Saturated Fat')),
                ('total_carbs', models.FloatField(help_text='Carbohydrate content (g).', verbose_name='Total Carbs')),
                ('fiber', models.FloatField(help_text='Fiber content (g).', verbose_name='Fiber')),
                ('sugar', models.FloatField(help_text='Sugar content (g).', verbose_name='Sugar')),
                ('sodium', models.FloatField(help_text='Sodium content (mg).', verbose_name='Sodium')),
                ('potassium', models.FloatField(help_text='Potassium content (mg).', verbose_name='Potassium')),
                ('cholesterol', models.FloatField(help_text='Cholesterol content (mg).', verbose_name='Cholesterol')),
                ('meal', models.ForeignKey(help_text='The meal this ingredient belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.meal')),
            ],
        ),
    ]
