# Generated by Django 5.2.8 on 2025-11-17 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date the mood was logged (must be unique for the user).', unique=True)),
                ('mood', models.IntegerField(help_text='The logged mood, on a scale from 1 to 10.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes on the mood.', null=True)),
                ('user', models.ForeignKey(help_text='The user who logged this mood.', on_delete=django.db.models.deletion.CASCADE, related_name='mood', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
