# Generated by Django 5.2.8 on 2025-11-28 16:12

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the mood was logged.'),
        ),
        migrations.AlterUniqueTogether(
            name='mood',
            unique_together={('user', 'date')},
        ),
        migrations.AlterModelTable(
            name='mood',
            table='moods',
        ),
    ]
