# Generated by Django 5.2.8 on 2025-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_alter_mood_options_alter_mood_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mood',
            table='mood',
        ),
    ]
