# Generated by Django 5.2.8 on 2025-11-17 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the workout was logged.')),
                ('workout_type', models.CharField(help_text='e.g., Running, Walking, Cycling.', max_length=50)),
                ('duration', models.IntegerField(help_text='Duration of the workout in minutes (or seconds, based on your logic).')),
                ('distance', models.FloatField(blank=True, help_text='Total distance covered.', null=True)),
                ('pace', models.FloatField(blank=True, help_text='Average pace for the workout.', null=True)),
                ('intensity', models.CharField(blank=True, help_text='Perceived intensity (Low, Medium, High).', max_length=20, null=True)),
                ('calories', models.FloatField(help_text='Estimated calories burned during the workout.')),
                ('user', models.ForeignKey(help_text='The user who logged this workout.', on_delete=django.db.models.deletion.CASCADE, related_name='logged_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_logged',
                'ordering': ['-date'],
            },
        ),
    ]
