# Generated by Django 5.2.8 on 2025-11-17 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.FloatField(blank=True, help_text='Total distance covered in kilometers.', null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(help_text='Duration of the workout in minutes.'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(blank=True, help_text='Perceived intensity (Low, Medium or High).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(help_text='The user who logged this workout.', on_delete=django.db.models.deletion.CASCADE, related_name='workout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='workout',
            table=None,
        ),
    ]
