# Generated by Django 5.2.8 on 2025-11-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_options_alter_workout_distance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelTable(
            name='workout',
            table='workout_logged',
        ),
    ]
