# Generated by Django 5.2.8 on 2025-11-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workout_options_alter_workout_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workout',
            table='workout',
        ),
    ]
